## Chapter 2 Lab

### Basic Commands

In [2]:
print("fit a model with", 11, "variables")

fit a model with 11 variables


In [3]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [4]:
3 + 5

8

In [5]:
"hello" + "world"

'helloworld'

In [6]:
# sequenecs lists and tuples
x = [3, 4, 5]
x

[3, 4, 5]

In [7]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

In [9]:
## Adding sequence data gives back concatenation - true of strings too

### Introduction to Numerical Python

In [11]:
%pip install numpy

  Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl.metadata (60 kB)
Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np

In [13]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [14]:
x + y

array([ 7, 13, 12])

In [16]:
# also possible to create matrices via multi-dimensional arrays

x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [18]:
x.ndim, x.dtype

(2, dtype('int64'))

In [20]:
# implicit data type conversions
x = np.array([[1, 2], [3.0, 4]])
x.dtype

dtype('float64')

In [21]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [22]:
np.array([[1, 2], [3, 4]], dtype=float).dtype

dtype('float64')

In [23]:
x.shape

(2, 2)

In [26]:
x.sum()  # implicitly passes x as the first argument to the method e.g. sum(self, ...)

np.float64(10.0)

In [27]:
np.sum(x)

np.float64(10.0)

In [28]:
# we can also reshape on the go too
x = np.array([1, 2, 3, 4, 5, 6])
print(x)
x_reshape = x.reshape((2, 3))
print(x_reshape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Notice that numpy cut the dataframe as a seqeunce of rows - not a sequence of columns first. This is called _row major ordering_.

In [30]:
x_reshape[0, 0]

np.int64(1)

In [31]:
x_reshape[1, 2]

np.int64(6)

In [32]:
x[3]

np.int64(4)

In [34]:
print(x_reshape)
x_reshape[0, 0] = 5
print(x_reshape)

[[1 2 3]
 [4 5 6]]
[[5 2 3]
 [4 5 6]]


In [35]:
print(x)

[5 2 3 4 5 6]


Notice that since _x_ and _x _ reshape_ point to the same place in memory, modifying that place modifies both.

Recall that tuples are not mutable so we have

In [37]:
y = (3, 4, 5)
y[0] = 2

TypeError: 'tuple' object does not support item assignment

In [38]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [39]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [40]:
x**2

array([25,  4,  9, 16, 25, 36])

In [41]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [42]:
# We can also randomly generate data

# normal random data
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [44]:
x = np.random.normal(size=50)
x

array([-0.93230525,  1.15415226,  2.345425  ,  0.34701473, -0.18367794,
        0.84070946,  0.52871946,  0.3124265 ,  0.94375236, -0.79683836,
       -0.58169344, -0.0931726 ,  1.23470654,  0.49378801,  0.86116695,
       -2.13489222, -2.27776071, -0.78684985,  0.7464952 ,  0.3479821 ,
       -0.03938126, -2.30878037,  0.25280371, -0.5023934 , -0.65121185,
        0.41767052,  0.14501507,  1.01085326, -0.39508961, -0.37561308,
        1.90311237, -1.10075158, -0.97612821,  0.13494495,  0.50784609,
       -0.34257389,  0.50480447,  0.88943124, -1.92557035, -0.17121948,
       -1.66822946, -2.22893469,  1.05790807, -0.29303062, -1.95205855,
        1.10471947, -0.78598444, -1.18678982, -0.79555294, -0.07121685])

In [ ]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [48]:
# correlation coefficient
np.corrcoef(x, y)

array([[1.        , 0.70088018],
       [0.70088018, 1.        ]])

In [49]:
# we have different seeds so
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))


[-1.73852581  5.50593231]
[-0.9240053 -4.5153519]


In [50]:
# we can set a random seed by
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))


[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [52]:
# we can use this to show how to get empirical moments

rng = np.random.default_rng(1234)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(np.float64(0.12748754499933185), np.float64(0.12748754499933185))

In [54]:
# variance - notice these are not biased corrected
np.var(y), y.var(), np.mean((y - y.mean()) ** 2)

(np.float64(1.8193289053764339),
 np.float64(1.8193289053764339),
 np.float64(1.8193289053764339))

In [55]:
# we can change this by setting the ddof argument
np.var(y, ddof=1), y.var(ddof=1)

(np.float64(2.021476561529371), np.float64(2.021476561529371))

In [56]:
np.sqrt(np.var(y)), y.std()

(np.float64(1.3488250091751834), np.float64(1.3488250091751834))

In [ ]:
# We can also apply these across the rows and columns of both of these matrices
